"""Puertos (interfaces) del contexto Brand Identity. La infraestructura
los implementa; el dominio no conoce Groq, Gemini ni Postgres."""
from typing import Optional, Protocol

from app.contexts.brand_identity.domain.models import (
    BrandManual,
    BrandRule,
    BrandSummary,
)


class TextLlmPort(Protocol):
    def generate(self, prompt: str) -> str: ...


class VectorStorePort(Protocol):
    def index(self, brand_id: str, rules: list[BrandRule]) -> None: ...
    def query(self, brand_id: str, text: str, k: int = 5) -> list[BrandRule]: ...
    def update_rule(self, brand_id: str, rule_id: int, rule: BrandRule) -> BrandRule: ...
    def add_rule(self, brand_id: str, rule: BrandRule) -> BrandRule: ...
    def delete_rule(self, brand_id: str, rule_id: int) -> None: ...


class BrandManualRepository(Protocol):
    def save(self, manual: BrandManual) -> None: ...
    def get(self, brand_id: str) -> Optional[BrandManual]: ...
    def list_all(self) -> list[BrandSummary]: ...
