"""Puertos del contexto Identity & Access."""
from typing import Optional, Protocol

from app.contexts.identity_access.domain.models import AuditLogEntry, Role, User


class UserRepository(Protocol):
    def create(self, user: User, password_hash: str) -> None: ...
    def get(self, user_id: str) -> Optional[User]: ...
    def by_email(self, email: str) -> Optional[User]: ...
    def password_hash(self, user_id: str) -> Optional[str]: ...
    def set_role(self, user_id: str, role: Role) -> None: ...
    def deactivate(self, user_id: str) -> None: ...
    def list_all(self) -> list[User]: ...


class PasswordHasher(Protocol):
    def hash(self, pw: str) -> str: ...
    def verify(self, pw: str, stored: str) -> bool: ...


class TokenService(Protocol):
    def issue(self, sub: str, rol: str, ttl_min: int = 120) -> str: ...
    def verify(self, token: str) -> dict: ...


class AuditLogRepository(Protocol):
    def add(self, entry: AuditLogEntry) -> None: ...
    def list_all(self) -> list[AuditLogEntry]: ...
